#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=37        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semibold:15.0"  \
                     icon.color=$TEXT_COLOR            \
                     label.font="SF Pro:Semibold:15.0" \
                     label.color=$TEXT_COLOR           \
                     background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=5            \
                     background.height=30                  \
                     padding_left=8                        \
                     padding_right=8                       \
                     label.padding_left=7                  \
                     label.padding_right=15                \
                     icon.padding_left=15                  \
                     icon.padding_right=7

# -- Left Side Items --
source $ITEM_DIR/aerospace_workspaces.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/focused_app.sh


##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
